version: '3'
services:
  scribe-ai-jobs-listener:
    image: scribe-ai-jobs-listener
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@localhost:5672/
      - RABBITMQ_QUEUE_NAME=your_queue_name
    deploy:
      replicas: 3
    restart: always
    networks:
      - your_network
      
networks:
  your_network:
    driver: bridge